name: SARS-Cov-2-Africa-dashboard
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - streamlit=1.2.0
  - pandas
  - xlrd=1.2.0
  - geopandas
  - geopy=2.2.0
  - plotly=5.5.0
  - backports.lzma=0.0.14
